### MYSQL_ROOT_PASSWORD 需要在执行docker-compose up -d 的时候将密码传进去

version: '3.8'
services:
  mysql:
    container_name: mysql57
    image: mysql:5.7.44
    restart: always
    ports:
      - 3306:3306
    privileged: true
    volumes:
      - /data/app/mysql5.7/data/conf/my.cnf:/etc/my.cnf
      - /data/app/mysql5.7/data/mysql-data:/var/lib/mysql
      - /data/app/mysql5.7/data/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
