version: "3.1"
services:
  redis7:
    image: redis:7.2.4
    container_name: redis7
    ports:
      - "6379:6379"
    volumes:
      - "/data/app/redis7/data/conf:/usr/local/etc/redis"
      - "/data/app/redis7/data/redis-data:/data"
      - "/data/app/redis7/data/logs:/logs"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
