version: "3"
services:
  mongodb:
    image: mongo:3.6.8
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/app/mongodb/data/mongodb-data:/data/db
      - /data/app/mongodb/data/conf:/data/configdb
      - /data/app/mongodb/data/logs:/data/logs
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=wAbEfnL6qkk2qhCa
