#### /data/app/kafka/kafka1/kafka-data 这个目录需要执行chmod -R 777 /data/app/kafka/kafka1/kafka-data

version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - /data/app/kafka/zookeeper/zookeeper-data:/data
      - /data/app/kafka/zookeeper/logs:/logs
      - /data/app/kafka/zookeeper/datalogs:/datalogs
    restart: always

  kafka1:
    image: bitnami/kafka:2.8.1
    container_name: kafka1
    user: root
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ZOOKEEPER_CONNECT: 172.31.29.247:2181
      ALLOW_PLAINTEXT_LISTENER: 'true'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.29.247:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 160
      KAFKA_ZOOKEEPER_PROTOCOL: 'PLAINTEXT'
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
    volumes:
      - /data/app/kafka/kafka1/kafka-data:/kafka/data
    restart: unless-stopped



  kafka2:
    image: bitnami/kafka:2.8.1
    container_name: kafka2
    user: root
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_ZOOKEEPER_CONNECT: 172.31.29.247:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.29.247:9093
      ALLOW_PLAINTEXT_LISTENER: 'true'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 160
      KAFKA_ZOOKEEPER_PROTOCOL: 'PLAINTEXT'
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9093"

    volumes:
      - /data/app/kafka/kafka2/kafka-data:/kafka/data
    restart: unless-stopped


  kafka3:
    image: bitnami/kafka:2.8.1
    container_name: kafka3
    user: root
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: '3'
      KAFKA_ZOOKEEPER_CONNECT: 172.31.29.247:2181
      ALLOW_PLAINTEXT_LISTENER: 'true'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.29.247:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 160
      KAFKA_ZOOKEEPER_PROTOCOL: 'PLAINTEXT'
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9094"
    volumes:
      - /data/app/kafka/kafka3/kafka-data:/kafka/data
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "172.31.29.247:9092,172.31.29.247:9093,172.31.29.247:9094"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "172.31.29.247:2181"
      KAFKA_CLUSTERS_0_READONLY: "false"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always
